name: interrupted
favicon: null
layout_spectrum: 0.21343404590152204
typography_spectrum: 0.3408286527264863
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7129126144573092
  lightness: 0.17575096082873642
  saturation: 0.5766392983496189
  rhythmicContrast: 0.8841897803358734
purpose: []
